version: 2.1

jobs:
  ubuntu2004:
    docker:
      - image: stbtester/circleci:ubuntu2004
    environment:
      python_version: 3
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - pylint
      - pytest
      - integrationtests

  ubuntu2204:
    docker:
      - image: stbtester/circleci:ubuntu2204
    environment:
      python_version: 3
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - pylint
      - pytest
      - integrationtests

  python-package:
    docker:
      - image: cimg/python:3.10.4
    environment:
      python_version: 3
      LANG: C.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - check-pythonpackage

commands:
  pylint:
    steps:
      - run:
          name: make check-pylint
          command: |
            tesseract --version
            make check-pylint
  pytest:
    steps:
      - run: make check-pytest
  integrationtests:
    steps:
      - run: make check-integrationtests
  check-pythonpackage:
    steps:
      - run: python3 setup.py sdist
      - run:
          name: install & test
          command: |
            rm -rf stbt_core _stbt &&
            python3 -m venv build_env &&
            source build_env/bin/activate &&
            pip3 install pytest==6.2.5 &&
            pip3 install dist/*.tar.gz &&
            make check-pythonpackage PYTEST=pytest

workflows:
  test_all:
    jobs:
      - python-package
      - ubuntu2004
      - ubuntu2204
